---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: download
  image: golang:1.15
  commands:
  - go mod download
  volumes:
  - name: gopath
    path: /go

- name: lint
  image: golang:1.15
  commands:
  - make lint
  volumes:
  - name: gopath
    path: /go
  depends_on:
  - download

- name: test
  image: golang:1.15
  commands:
  - make test
  volumes:
  - name: gopath
    path: /go
  depends_on:
  - download

...
